// Runs an isolated preview with the real MOD files. Requires Playwright in NODE_PATH.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
(async()=>{
  const server=spawn(process.execPath,[require('node:path').join(__dirname,'mesa-preview.cjs')],{env:{...process.env,MESA_PORT:'0'},stdio:['ignore','pipe','inherit']});
  process.on('exit',()=>server.kill());
  const address=await new Promise((resolve,reject)=>{server.stdout.once('data',chunk=>resolve(String(chunk).trim().split(' ').at(-1)));server.once('error',reject);server.once('exit',code=>reject(new Error('Preview exited: '+code)));});
  const browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  await page.addInitScript(()=>{
    window.__audioStarts=0;window.__audioStops=0;
    window.__cspViolations=[];document.addEventListener('securitypolicyviolation',e=>window.__cspViolations.push(e.violatedDirective));
    const gain=AudioContext.prototype.createGain;
    AudioContext.prototype.createGain=function(){const g=gain.call(this);if(!window.__analyser){window.__analyser=this.createAnalyser();window.__audioContext=this;g.connect(window.__analyser);window.__analyser.connect(this.destination);}return g;};
    const create=AudioContext.prototype.createOscillator;
    AudioContext.prototype.createOscillator=function(){const o=create.call(this),start=o.start.bind(o),stop=o.stop.bind(o);o.start=(...args)=>{window.__audioStarts++;return start(...args);};o.stop=(...args)=>{window.__audioStops++;return stop(...args);};return o;};
  });
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(address);
  await page.getByRole('button',{name:'MESA',exact:true}).click();
  await page.getByRole('button',{name:'CRIAR CAMPANHA'}).click();
  await page.getByLabel('Nome da campanha').fill('O Observatório Vazio');
  await page.getByRole('button',{name:'Criar',exact:true}).click();
  await page.getByRole('button',{name:'Fichas',exact:true}).click();
  await page.getByRole('button',{name:'Nova ficha'}).click();
  await page.getByLabel('Personagem',{exact:true}).fill('Iria');
  await page.locator('[name=owner]').selectOption('2');
  await page.getByRole('button',{name:'Criar',exact:true}).click();
  await page.getByRole('button',{name:'Abrir ficha'}).click();
  await page.getByLabel('Classe / multiclasse').fill('Maga');
  await page.getByLabel('Nível',{exact:true}).fill('3');
  await page.getByLabel('DES',{exact:true}).fill('16');
  await page.getByRole('button',{name:'Salvar ficha'}).click();
  await page.getByRole('button',{name:'Proficiências',exact:true}).click();
  await page.getByLabel('Furtividade · Destreza',{exact:true}).selectOption('2');
  await page.getByRole('button',{name:'Salvar proficiências'}).click();
  await page.getByRole('button',{name:'Jogar',exact:true}).click();
  await page.getByLabel('Teste',{exact:true}).selectOption('skill:stealth');
  await page.getByLabel('Modo de rolagem').selectOption('advantage');
  assert.match(await page.locator('[name=test] option:checked').textContent(),/Furtividade \(\+7\)/);
  await page.getByRole('button',{name:'Rolar e registrar'}).click();
  async function vitality(kind,amount) {
    await page.getByRole('button',{name:'Jogar',exact:true}).click();
    await page.getByRole('button',{name:'Dano / cura'}).click();
    await page.getByLabel('Operação').selectOption(kind);
    await page.getByLabel('Quantidade').fill(String(amount));
    await page.getByRole('button',{name:'Aplicar',exact:true}).click();
  }
  await vitality('temporary',5);await vitality('damage',8);
  await page.getByText('Maga · PV 7/10 · CA 10',{exact:true}).waitFor();
  await vitality('heal',99);
  await page.getByText('Maga · PV 10/10 · CA 10',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Jogar',exact:true}).click();
  await page.getByRole('button',{name:'Condições',exact:true}).click();
  await page.getByLabel('Uma condição por linha').fill('Concentrando\nEfeito privado de Iria');
  await page.getByRole('button',{name:'Salvar condições'}).click();
  await page.getByText('Concentrando · Efeito privado de Iria',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Retrato',exact:true}).click();
  await page.locator('input[type=file]').setInputFiles({name:'iria.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aCr8AAAAASUVORK5CYII=','base64')});
  await page.getByRole('button',{name:'Salvar retrato'}).click();
  await page.getByRole('img',{name:'Retrato de Iria'}).waitFor();
  await page.getByRole('button',{name:'Retrato',exact:true}).click();
  await page.getByRole('button',{name:'Publicar retrato'}).click();
  await page.getByRole('button',{name:'Confirmar',exact:true}).click();
  await page.getByRole('button',{name:'Ações',exact:true}).click();
  await page.getByRole('button',{name:'Nova ação',exact:true}).click();
  await page.getByLabel('Nome da ação').fill('Arco curto');
  await page.getByLabel('Fórmula opcional').fill('1d20+5');
  await page.getByLabel('Usos máximos (0 = livre)',{exact:true}).fill('1');
  await page.getByLabel('Recuperação',{exact:true}).selectOption('long');
  await page.getByRole('button',{name:'Salvar ação'}).click();
  await page.getByRole('button',{name:'Jogar',exact:true}).click();
  await page.getByRole('button',{name:'Usar Arco curto',exact:true}).click();
  await page.getByRole('button',{name:'Usar e registrar',exact:true}).click();
  await page.getByRole('button',{name:'Jogar',exact:true}).click();
  await page.getByText('1d20+5 · 0/1 usos',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Descanso longo',exact:true}).click();
  await page.getByRole('button',{name:'Confirmar descanso'}).click();
  await page.getByRole('button',{name:'Compêndio',exact:true}).click();
  await page.getByRole('button',{name:'Novo conteúdo'}).click();
  await page.getByLabel('Nome',{exact:true}).fill('Centelha da campanha');
  await page.getByLabel('Descrição — conteúdo próprio ou autorizado').fill('Uma luz criada pelo GM para esta campanha.');
  await page.getByLabel('Publicar para os jogadores').check();
  await page.getByRole('button',{name:'Salvar',exact:true}).click();
  await page.getByRole('heading',{name:'Centelha da campanha'}).waitFor();
  await page.getByRole('button',{name:'Preparação',exact:true}).click();
  await page.getByRole('button',{name:'Novo mapa'}).click();
  await page.getByLabel('Nome',{exact:true}).fill('Câmara superior');
  await page.getByRole('button',{name:'Criar',exact:true}).click();
  await page.getByRole('button',{name:'Importar imagem'}).click();
  await page.locator('input[type=file]').setInputFiles({name:'mapa.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aCr8AAAAASUVORK5CYII=','base64')});
  await page.getByRole('button',{name:'Importar',exact:true}).click();
  await page.getByRole('button',{name:'Abrir',exact:true}).click();
  await page.locator('.mesa-map>img').waitFor();
  await page.getByRole('button',{name:'Adicionar peça'}).click();
  await page.locator('[name=sheet]').selectOption({label:'Iria'});
  await page.getByLabel('Oculta aos jogadores').uncheck();
  await page.getByRole('button',{name:'Adicionar',exact:true}).last().click();
  await page.locator('.mesa-piece img').waitFor();
  await page.getByRole('button',{name:'Revelar',exact:true}).click();
  await page.getByRole('button',{name:'Escolher trilha'}).click();
  await page.getByLabel('Trilha',{exact:true}).selectOption('exploration');
  await page.getByRole('button',{name:'Tocar para a mesa'}).click();
  assert.equal(await page.evaluate(()=>window.__audioStarts),0,'audio must require local opt-in');
  await page.getByRole('button',{name:'Ativar som neste dispositivo'}).click();
  await page.waitForFunction(()=>window.__audioStarts>0);
  await page.waitForFunction(()=>{const samples=new Float32Array(window.__analyser.fftSize);window.__analyser.getFloatTimeDomainData(samples);return samples.some(v=>Math.abs(v)>.0001);});
  await page.getByRole('button',{name:'Pausar para todos'}).click();
  await page.getByText('Exploração · pausado',{exact:true}).waitFor();
  await page.waitForTimeout(300);const pausedStarts=await page.evaluate(()=>window.__audioStarts);
  await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>window.__audioStarts),pausedStarts);
  await page.getByRole('button',{name:'Retomar para todos'}).click();
  await page.getByRole('button',{name:'Adicionar',exact:true}).click();
  await page.locator('select[name=sheet]').selectOption({label:'Iria'});
  await page.getByLabel('Resultado').fill('19');
  await page.getByRole('button',{name:'Adicionar',exact:true}).last().click();
  await page.locator('.mesa-turn img').waitFor();
  await page.getByRole('button',{name:'ROLAR',exact:true}).click();
  await page.getByText(/1d20 =/).waitFor();
  const token=page.getByRole('button',{name:'Iria',exact:true});
  const box=await page.locator('.mesa-map').boundingBox();
  await token.hover();await page.mouse.down();await page.mouse.move(box.x+box.width*.45,box.y+box.height*.65);await page.mouse.up();
  await page.waitForTimeout(400);
  const pos=await token.evaluate(el=>({left:el.style.left,top:el.style.top}));
  assert.ok(parseFloat(pos.left)>40);assert.ok(parseFloat(pos.top)>60);
  await page.screenshot({path:'/tmp/mesa-v1-desktop.png',fullPage:true});
  const player=await browser.newPage({viewport:{width:1280,height:900}});player.on('pageerror',e=>errors.push(e.message));
  await player.goto(address);await player.getByRole('combobox').selectOption('2');await player.getByRole('button',{name:'MESA',exact:true}).click();
  await player.getByRole('heading',{name:'Câmara superior'}).waitFor();
  await player.locator('.mesa-piece img').waitFor();
  await player.getByText('Exploração · tocando',{exact:true}).waitFor();
  assert.equal(await player.getByRole('button',{name:'Escolher trilha'}).count(),0);
  assert.equal(await player.getByRole('button',{name:'Preparação',exact:true}).count(),0);
  await player.getByRole('button',{name:'Fichas',exact:true}).click();await player.getByRole('button',{name:'Abrir ficha'}).click();
  assert.equal(await player.getByLabel('Classe / multiclasse').inputValue(),'Maga');
  await player.getByRole('button',{name:'Fechar',exact:true}).last().click();
  await player.getByRole('button',{name:'Jogar',exact:true}).click();
  await player.getByText('Concentrando · Efeito privado de Iria',{exact:true}).last().waitFor();
  await player.getByLabel('Teste',{exact:true}).selectOption('save:wis');
  await player.getByLabel('Modo de rolagem').selectOption('disadvantage');
  await player.getByRole('button',{name:'Rolar e registrar'}).click();
  const outsider=await browser.newPage();await outsider.goto(address);
  await outsider.getByRole('combobox').selectOption('3');await outsider.getByRole('button',{name:'MESA',exact:true}).click();
  await outsider.getByRole('heading',{name:'Câmara superior'}).waitFor();
  assert.ok(!(await outsider.locator('body').textContent()).includes('Efeito privado de Iria'));
  await outsider.locator('.mesa-piece img').waitFor();
  const currentRevision=(await outsider.locator('.mesa-footer').innerText()).match(/REVISÃO (\d+)/)[1];
  await page.waitForFunction(revision=>document.querySelector('.mesa-footer').innerText.includes('REVISÃO '+revision),currentRevision);
  await page.getByRole('button',{name:'Fichas',exact:true}).click();
  await page.getByRole('button',{name:'Retrato',exact:true}).click();
  await page.getByRole('button',{name:'Tornar retrato privado'}).click();
  await page.getByRole('button',{name:'Confirmar',exact:true}).click();
  await page.locator('dialog').waitFor({state:'hidden'});
  await outsider.locator('.mesa-piece img').waitFor({state:'detached'});
  await page.getByRole('button',{name:'Preparação',exact:true}).click();
  await page.getByRole('button',{name:'Trilha da cena'}).click();
  await page.getByLabel('Trilha',{exact:true}).selectOption('mystery');
  await page.getByRole('button',{name:'Vincular à cena'}).click();
  await page.getByRole('button',{name:'Revelar',exact:true}).click();
  await outsider.getByText('Mistério · tocando',{exact:true}).waitFor();
  await player.setViewportSize({width:720,height:700});
  assert.equal(await player.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  assert.deepEqual(errors,[]);
  assert.deepEqual(await page.evaluate(()=>window.__cspViolations),[]);
  await page.getByRole('button',{name:'Voltar ao SEELE'}).click();
  await page.waitForTimeout(300);const stoppedStarts=await page.evaluate(()=>window.__audioStarts);
  await page.waitForTimeout(600);assert.equal(await page.evaluate(()=>window.__audioStarts),stoppedStarts);
  await page.getByRole('button',{name:'MESA',exact:true}).click();
  await page.waitForFunction(n=>window.__audioStarts>n,stoppedStarts);
  await page.route('**/request',route=>route.abort());
  await page.waitForTimeout(8500);const offlineStarts=await page.evaluate(()=>window.__audioStarts);
  await page.waitForTimeout(1000);assert.equal(await page.evaluate(()=>window.__audioStarts),offlineStarts,'stale sessions stop scheduling audio');
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('seele-mod-unload',{detail:'seele/mesa'})));
  await page.waitForFunction(()=>window.__audioContext.state==='closed');
  const legacy=await browser.newPage();legacy.on('pageerror',e=>errors.push(e.message));
  await legacy.addInitScript(()=>{window.CSSStyleSheet=function(){throw new Error('Legacy WebView');};});
  await legacy.goto(address);await legacy.getByRole('button',{name:'MESA',exact:true}).click();
  assert.equal(await legacy.locator('.mesa-root').evaluate(e=>getComputedStyle(e).position),'fixed');
  await legacy.evaluate(()=>window.dispatchEvent(new CustomEvent('seele-mod-unload',{detail:'seele/mesa'})));
  assert.equal(await legacy.locator('#seele-mesa-launch').count(),0);
  assert.equal(await legacy.evaluate(()=>Array.from(document.styleSheets).some(s=>Array.from(s.cssRules).some(r=>r.cssText.includes('.mesa-')))),false);
  assert.deepEqual(errors,[]);
  console.log('UI passed under CSP: portraits, publication, character actions/resources, local audio opt-in, GM pause/resume, player sync, close stops audio, plus existing RPG flow.');
  await browser.close();
  server.kill();
})().catch(e=>{console.error(e);process.exit(1)});
